### ISSUE TITLE
長い提出が見られない

### ISSUE THREAD

**Issue by tomo-224** [atsuo-tech/atsuo-coder#25]
任意の提出ページで、`<div class = "submission_root__...">` の中の `<iframe id="ace-editor" class="submission_reader__..." ` の後の `src` に直接提出コードが埋め込まれているためか、長い提出を読み込むことができない。

**Comment by yama-can** [comment]
[コミット](https://github.com/atsuo-tech/atsuo-coder/pull/30/commits/63d8daff28a17ed607231acf859fdc61a8e232b7) により修正されました。
#30
